# Generated by Django 3.2.7 on 2022-01-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact',
        ),
    ]
