# Generated by Django 3.2.7 on 2022-01-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_updateorder_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorder',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
